- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: devopswithaws.store
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: Allow-everything
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    loop:
    - db
    - backend
    - frontend
    register: ec2_instances_info
  
  - name: print output
    ansible.builtin.debug:
      msg: "output: {{ ec2_instances_info }}"


  #- name: create r53 records
   # amazon.aws.route53: